# Generated by Django 6.0.6 on 2026-06-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='businesses.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='products.product')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_categories', to='analytics.customerreview')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('revenue_declining', 'Revenue Declining'), ('competitor_price_lower', 'Competitor Price Lower'), ('growing_demand', 'Growing Market Demand'), ('inventory_risk', 'Inventory Risk')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='businesses.business')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('sales_forecast', 'Sales Forecast'), ('product_risk', 'Product Risk'), ('business_health', 'Business Health Score'), ('demand_forecast', 'Demand Forecast')], max_length=30)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='businesses.business')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='analytics.customerreview')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_point', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('business', 'product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('business', 'product', 'date')},
            },
        ),
    ]
