# Generated by Django 6.0.6 on 2026-07-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('integrations', '0002_importbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='integrations.importbatch'),
        ),
        migrations.AddField(
            model_name='insight',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='integrations.importbatch'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='integrations.importbatch'),
        ),
    ]
