# Generated by Django 6.0.6 on 2026-07-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_customerreview_import_batch_insight_import_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='cost',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
