# Generated by Django 6.0.6 on 2026-07-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_unit_price_remove_cost_field'),
        ('integrations', '0002_importbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='integrations.importbatch'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='integrations.importbatch'),
        ),
    ]
