# Generated by Django 6.0.6 on 2026-08-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_insight_market_intelligence'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_record_count', models.IntegerField(help_text='Number of SalesRecords used for the last training run.')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='businesses.business')),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
    ]