# Generated by Django 6.0.6 on 2026-08-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_traininghistory'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_record_changes', to='businesses.business')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]