# Generated by Django 6.0.6 on 2026-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_salesrecordchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('revenue_declining', 'Revenue Declining'), ('competitor_price_lower', 'Competitor Price Lower'), ('growing_demand', 'Growing Market Demand'), ('declining_demand', 'Declining Market Demand'), ('market_intelligence', 'Market Intelligence'), ('market_intel_existing', 'Market Intelligence - Existing Product'), ('market_intel_opportunity', 'Market Intelligence - Opportunity Keyword'), ('inventory_risk', 'Inventory Risk')], max_length=30),
        ),
    ]
