# Generated by Django 6.0.6 on 2026-08-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_insight_insight_type'),
        ('analytics', '0010_alter_insight_insight_type'),
    ]

    operations = [
    ]
