# Generated by Django 6.0.6 on 2026-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
    ]
