# Generated by Django 6.0.6 on 2026-06-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='products.product')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('reviews', 'Reviews')], max_length=20)),
                ('original_column', models.CharField(max_length=100)),
                ('mapped_column', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='businesses.business')),
            ],
            options={
                'ordering': ['source_type', 'original_column'],
                'unique_together': {('business', 'source_type', 'original_column')},
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('interest_score', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_trends_data', to='businesses.business')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('business', 'keyword', 'region', 'date')},
            },
        ),
    ]
