# Generated by Django 6.0.6 on 2026-08-03 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_importbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrendsdata',
            name='fetched_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='googletrendsdata',
            name='region',
            field=models.CharField(default='worldwide', max_length=100),
        ),
    ]
