# Generated by Django 6.0.6 on 2026-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_googletrendsdata_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorprice',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
