# Generated by Django 6.0.6 on 2026-08-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_owner'),
        ('integrations', '0004_alter_competitorprice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_keywords', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'keyword')},
            },
        ),
    ]
